name: CI
on:
  push:
    branches: [main]
jobs:
  deploy:
    name: "Deploy to staging"
    runs-on: self-hosted
    environment: work
    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
          cat >>~/.ssh/config <<END
          Host staging
              HostName $SSH_HOST
              User $SSH_USER
              Port $SSH_PORT
              IdentityFile ~/.ssh/staging.key
              StrictHostKeyChecking no
          END
      - name: File creation
        run: |
          mkdir -p apps/web/.next/static/
          echo "text" >> apps/web/.next/static/test
          mkdir -p apps/web/public/
          echo "text" >> apps/web/public/test
      - name: Send build to server
        run: rsync -rvz -e "ssh" apps/web/.next/static/ staging:/var/www/html/site/apps/web/.next/standalone/apps/web/.next/static --delete
      - name: Send public to server
        run: rsync -rvz -e "ssh" apps/web/public/ staging:/var/www/html/site/apps/web/.next/standalone/apps/web/public --delete
      - name: Services restart
        run: which cat || ssh staging 'sudo systemctl restart apio-api apio-web'
