name: CI
on:
  - push
jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - name: "No tests"
        run: "echo No tests has been setup"
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    environment: work
    if: github.ref == 'refs/heads/main'
    needs: test
    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
          cat >>~/.ssh/config <<END
          Host staging
              HostName $SSH_HOST
              User $SSH_USER
              Port $SSH_PORT
              IdentityFile ~/.ssh/staging.key
              StrictHostKeyChecking no
          END
      - name: Check SSH Configure
        run: cat ~/.ssh/config
      - name: Stop the server
        run: ssh staging 'echo Stop'
      - name: Check out the source
        run: ssh staging 'cd workflow && git fetch && git reset --hard origin/main'
      - name: Start the server
        if: ${{ always() }}
        run: ssh staging 'echo Start'
