name: CI
on:
  push:
    branches: [main]
jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
    - name: "Install Nodejs Check"
      run: |
        which node || ( curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash )
        source ~/.bashrc
        nvm install 20
        nvm use 20
        nvm alias default 20
    - name: "Install Nodejs Check"
      run: "which node"
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    environment: work
    #needs: test
    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
          cat >>~/.ssh/config <<END
          Host staging
              HostName $SSH_HOST
              User $SSH_USER
              Port $SSH_PORT
              IdentityFile ~/.ssh/staging.key
              StrictHostKeyChecking no
          END
      - name: Check SSH Configure
        run: cat ~/.ssh/config
      - name: Stop the server
        run: ssh staging 'echo Stop'
      - name: Check out the source
        run: ssh staging 'cd workflow && git fetch && git reset --hard origin/main'
      - name: Start the backend
        if: ${{ always() }}
        run: ssh staging 'cd ~/workflow/apps/api && node --env-file=.env dist/index.js'
      - name: Start the frontend
        if: ${{ always() }}
        env:
          API_URL=http://localhost:4000
          SITE_URL=https://runner.axel-gros.tech
          HOSTNAME=0.0.0.0
          PORT=3000
          DISALLOW_ROBOTS=false
        run: ssh staging 'cd ~/workflow/apps/web/.next/standalone && node apps/web/server.js'
